### PR TITLE
Inject client SAML name into the credentials instead of the default.

### PR DESCRIPTION
**Pull request by peyo**
When the credentials are built by pac4j, it is not with the "real client name" but with the class name : SAML2.class.getSimpleName(). 

This is boring if you specify the name or if you use 2 SAML clients.

This is not the best solution to resolve my problem but it works.
The best solution is to inject the client name when the credentials are built, into the function : #SAML2DefaultResponseValidator.buildSAML2Credentials().

Bye.

### CODE REVIEW

**Comment by leleuj** [comment]
We don't plan any work on 1.7 (we are about to start the development of version 1.9). Can you upgrade to version 1.8 where this has been fixed?

**Comment by peyo** [comment]
It's not possible for me to upgrade on 1.8 because I use pac4j with CAS server and it seems that version is not compatible with stable version of CAS. But, I may be wrong.

**Comment by leleuj** [comment]
pac4j should be compatible with any CAS server version unless there is a bug. What's your CAS server version? What's the issue?

**Comment by peyo** [comment]
I use the version 4.1.3 of CAS (with Tomcat 7).
If I use pac4j 1.8.2 it's impossible to start my server : NoClassDefFoundError: org/pac4j/core/client/Mechanism 
"Mechanism" class is referenced in the "cas-server-support-pac4j" jar (version 4.1.3 like CAS).
I make a mistake in my dependencies ?

**Comment by leleuj** [comment]
OK. I get it now: yes, inside the CAS server 4.1, you need pac4j v1.7.x. I will merge your PR, let you test pac4j v1.7.2-SNAPSHOT and if you confirm the fix, I'll cut a release.

Sounds good?

**Comment by peyo** [comment]
It's good (I use source not the SNAPSHOT Jar)
Do you know pac4j works with ADFS 3.0 (it seems not) ? 
Thx

**Comment by leleuj** [comment]
I'm not sure, but I think so. There is a specific documentation for ADFS, but it might outdated: https://github.com/pac4j/pac4j/blob/master/README-ADFS.txt

What issue do you have? Is there a way for me to test your configuration (online ADFS)?

**Comment by peyo** [comment]
Excuse me, it's just a bad ADFS configuration.
The ADFS don't send Subject NameID node and it cause NullPointerException in Pac4J.
I make a PullRequest for avoid it.

**Comment by leleuj** [comment]
Would you mind updating the `README- ADFS` doc with your latest updates? It could help others.
