### ISSUE TITLE
Incompatibility issues

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#222]
- between JWT and OpenID Connect supports (because of the Nimbus library):

```
[WARNING] Error for /callback
java.lang.NoSuchMethodError: com.nimbusds.jwt.SignedJWT.getHeader()Lcom/nimbusds/jose/ReadOnlyJWSHeader;
	at com.nimbusds.openid.connect.sdk.util.DefaultJWTDecoder.verify(DefaultJWTDecoder.java:136)
	at com.nimbusds.openid.connect.sdk.util.DefaultJWTDecoder.decodeJWT(DefaultJWTDecoder.java:217)
	at org.pac4j.oidc.client.OidcClient.retrieveUserProfile(OidcClient.java:316)
	at org.pac4j.oidc.client.OidcClient.retrieveUserProfile(OidcClient.java:88)
	at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:98)
```

- between CAS and SAML supports (because of the OpenSAML library): should be fixed by https://github.com/pac4j/pac4j/issues/213:

```
Caused by: java.lang.ClassCastException: org.opensaml.xml.schema.impl.XSAnyBuilder cannot be cast to org.opensaml.core.xml.XMLObjectBuilder
	at org.opensaml.core.xml.config.XMLConfigurator.initializeObjectProviders(XMLConfigurator.java:238) ~[opensaml-core-3.1.1.jar:na]
	at org.opensaml.core.xml.config.XMLConfigurator.load(XMLConfigurator.java:203) ~[opensaml-core-3.1.1.jar:na]
	at org.opensaml.core.xml.config.XMLConfigurator.load(XMLConfigurator.java:188) ~[opensaml-core-3.1.1.jar:na]
```

**Comment by leleuj** [comment]
Hint: https://github.com/pac4j/pac4j/issues/226

**Comment by leleuj** [comment]
Reverting minbus-jose-jwt to version 2.26.1 should work with oauth2-oidc-sdk v3.4.1.

**Comment by leleuj** [comment]
To fix JWT / OpenID Connect compatibility issue: https://github.com/pac4j/pac4j/pull/266

**Comment by leleuj** [comment]
CAS / SAML incompatibility (because of opensaml) fixed by: https://github.com/pac4j/pac4j/pull/270
